<a href="https://colab.research.google.com/github/sathishsivam/Gemini-/blob/main/LORA_Model_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
import numpy as np
_=torch.manual_seed(0)

Generating a Rank Deficient Matrix W

In [3]:
d,k=10,10
W_rank=2
W=torch.randn(d,W_rank) @ torch.randn(W_rank,k)

In [4]:
W

tensor([[-1.0797,  0.5545,  0.8058, -0.7140, -0.1518,  1.0773,  2.3690,  0.8486,
         -1.1825, -3.2632],
        [-0.3303,  0.2283,  0.4145, -0.1924, -0.0215,  0.3276,  0.7926,  0.2233,
         -0.3422, -0.9614],
        [-0.5256,  0.9864,  2.4447, -0.0290,  0.2305,  0.5000,  1.9831, -0.0311,
         -0.3369, -1.1376],
        [ 0.7900, -1.1336, -2.6746,  0.1988, -0.1982, -0.7634, -2.5763, -0.1696,
          0.6227,  1.9294],
        [ 0.1258,  0.1458,  0.5090,  0.1768,  0.1071, -0.1327, -0.0323, -0.2294,
          0.2079,  0.5128],
        [ 0.7697,  0.0050,  0.5725,  0.6870,  0.2783, -0.7818, -1.2253, -0.8533,
          0.9765,  2.5786],
        [ 1.4157, -0.7814, -1.2121,  0.9120,  0.1760, -1.4108, -3.1692, -1.0791,
          1.5325,  4.2447],
        [-0.0119,  0.6050,  1.7245,  0.2584,  0.2528, -0.0086,  0.7198, -0.3620,
          0.1865,  0.3410],
        [ 1.0485, -0.6394, -1.0715,  0.6485,  0.1046, -1.0427, -2.4174, -0.7615,
          1.1147,  3.1054],
        [ 0.9088,  

In [7]:
# Evaluate the rank of matrix W

W_rank=np.linalg.matrix_rank(W)
W_rank

2

**Now we are going to decompose this matrix by an algorithm called SVD Which means Singular Value Decomposition,which produces three matrices u s v when multiplied together they give us W , but the dimension of these decomposed matrices are much smaller based on the rank **

In [8]:
# Perform Singular Value Decomposition on W (W=u*s*v^T)
u,s,v=torch.svd(W)

In [33]:
u

tensor([[-0.4130,  0.0610,  0.8735,  0.0523,  0.0055,  0.1452, -0.0751, -0.1798,
         -0.0272, -0.0164],
        [-0.1299, -0.0221,  0.0303, -0.4812, -0.2519,  0.2625, -0.0212,  0.5134,
         -0.3179,  0.5028],
        [-0.2440, -0.4687, -0.0597,  0.7109, -0.1705, -0.1268, -0.1624,  0.2864,
         -0.1610,  0.1801],
        [ 0.3458,  0.4616,  0.1838,  0.2170, -0.6189, -0.0573, -0.1601,  0.2836,
          0.2950, -0.0836],
        [ 0.0355, -0.1535,  0.0391, -0.0458,  0.1397, -0.0743, -0.1325, -0.1231,
          0.7134,  0.6363],
        [ 0.2704, -0.3220,  0.2972,  0.0064,  0.0328, -0.0857,  0.7762,  0.3069,
          0.1533, -0.0786],
        [ 0.5448, -0.0423,  0.2849, -0.0307,  0.1086, -0.5028, -0.1895, -0.1721,
         -0.4521,  0.2911],
        [-0.0405, -0.4159,  0.1116, -0.3984,  0.0174, -0.3153, -0.4487,  0.3198,
          0.2185, -0.4508],
        [ 0.4071,  0.0109,  0.1229,  0.2090,  0.5239,  0.5625, -0.2801,  0.3187,
          0.0066, -0.0660],
        [ 0.3081, -

In [13]:

u_r=u[:,:W_rank]


In [14]:
u_r

tensor([[-0.4130,  0.0610],
        [-0.1299, -0.0221],
        [-0.2440, -0.4687],
        [ 0.3458,  0.4616],
        [ 0.0355, -0.1535],
        [ 0.2704, -0.3220],
        [ 0.5448, -0.0423],
        [-0.0405, -0.4159],
        [ 0.4071,  0.0109],
        [ 0.3081, -0.5108]])

In [34]:
s_r

tensor([[11.3851,  0.0000],
        [ 0.0000,  4.8439]])

In [15]:
s_r=torch.diag(s[:W_rank])

In [16]:
s_r

tensor([[11.3851,  0.0000],
        [ 0.0000,  4.8439]])

In [35]:
v_r

tensor([[ 0.2267, -0.1349, -0.2220,  0.1417,  0.0240, -0.2256, -0.5189, -0.1668,
          0.2422,  0.6737],
        [-0.0459, -0.2695, -0.8052, -0.1607, -0.1310,  0.0559, -0.2386,  0.2178,
         -0.1480, -0.3233]])

In [36]:
v_r=v[:,:W_rank].t()

In [37]:
v_r

tensor([[ 0.2267, -0.1349, -0.2220,  0.1417,  0.0240, -0.2256, -0.5189, -0.1668,
          0.2422,  0.6737],
        [-0.0459, -0.2695, -0.8052, -0.1607, -0.1310,  0.0559, -0.2386,  0.2178,
         -0.1480, -0.3233]])

In [19]:
B=u_r@s_r

In [20]:
A=v_r

In [24]:
B.shape

torch.Size([10, 2])

In [25]:
A.shape

torch.Size([2, 10])

In [26]:
bias=torch.randn(d)
x=torch.randn(d)

In [27]:
y=W@x+bias

In [28]:
y_prime=(B@A)@x+bias

In [29]:
print("original y using W\n",y)
print("")
print("y computed using BA\n",y_prime)

original y using W
 tensor([ 7.2684e+00,  2.3162e+00,  7.7151e+00, -1.0446e+01, -8.1639e-03,
        -3.7270e+00, -1.1146e+01,  2.0207e+00, -9.6258e+00, -4.1163e+00])

y computed using BA
 tensor([ 7.2684e+00,  2.3162e+00,  7.7151e+00, -1.0446e+01, -8.1638e-03,
        -3.7270e+00, -1.1146e+01,  2.0207e+00, -9.6258e+00, -4.1163e+00])


In [31]:
print("Total parameters of W",W.nelement())

Total parameters of W 100


In [32]:
print("Total parameter and B and A",B.nelement()+A.nelement())

Total parameter and B and A 40


reference

Umar Jamil LORA-Low Rank Adaptation of Large Language Models